path_classifiers:
  test: "test"
  include: "include"
  docs:
  - "docs"
  - "README.md"
  - "LICENSE"
extraction:
  cpp:
    configure:
      command:
      - "mkdir build"
      - "cd build"
      - "cmake .. -DBUILD_TESTS=True"
    index:
      build_command:
      - "cd build"
      - "make"
